### PR TITLE
Prep for release

### PR DESCRIPTION
**Pull request by lukaszkorecki**
[Given that the Java version of Sqids is going to be released to Maven soon](https://github.com/sqids/sqids-java/issues/5), I figured I can kick off the process for the Clojure version.

Right now the goal is to have a JVM Clojure wrapper, eventually implementing ClojureScript (or any other dialect) version.

All tests are passing, and the API is simple enough. For now, the scripts download the unpublished Jar from Maven. Once stable release is made I'll update the README and build + release process.

### CODE REVIEW

**Comment by 4kimov** [comment]
Hi @lukaszkorecki, have you seen PR #1 by @robhanlon22?

**Comment by lukaszkorecki** [comment]
@4kimov ah, no - I haven't! What a timing. From my POV I went with the simplest implementation possible, and with the simplest setup, but up to you which one you want to pick as the basis 👍

**Comment by 4kimov** [comment]
@lukaszkorecki Appreciate the effort. I've sent @robhanlon22 maintainer invite since they were first, so I think we should wait for PR #1 to land. In the meantime, I suggest we keep PR #2 open + I'm sure there will be improvements to push either way (just like in any other Sqids repo).

**Comment by lukaszkorecki** [comment]
@4kimov no worries, I'l be more than happy to help out 👍

**Comment by robhanlon22** [comment]
hey @lukaszkorecki, i just merged #1, but any changes and improvements would be very much appreciated! i'm considering moving the spec stuff out into its own namespace to reduce clutter.

**Comment by lukaszkorecki** [comment]
@robhanlon22 definitely +1 on moving specs to own namespace, it does clean up the code substantially. Other than that I'll can close this PR as it doesn't add anything really.

The only two things I'd suggest would be to:

- move off `clojure` as part of the namespace name. I'd expect `sqids.core` as the main ns to require just like most of the ecosystem does

- add dependency caching + use pre-built Clojure Docker image in Actions config to speed things up a bit, especially because there's a bunch of dev dependencies that are only used for linting and formatting being pulled every time the CI runs


Admittedly, the second one is super minor, IMHO, it's definitely more of a "me" thing ;-))

**Pull request closed without merging**
